[package]
name = "pit-builder-native"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "C and C++ WASI Component builders"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
pit-artifact = { path = "../pit-artifact" }
pit-builder-core = { path = "../pit-builder-core" }
sha2.workspace = true
tokio.workspace = true
