# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
This interface defines a handler of incoming HTTP Requests. It should
be exported by components which can respond to HTTP Requests.
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some


