[package]
name = "pit-builder-rust"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "PitFast Rust to WASI Preview 1 or Preview 2 builder adapter"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
pit-crew = { path = "../pit-crew" }
pit-artifact = { path = "../pit-artifact" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
wasmparser.workspace = true
